### ISSUE TITLE
Consider renaming repo to not start with dash

### ISSUE THREAD

**Issue by pjoe** [kainino0x/glslang.js#3]
With normal git clone this will end up in a directory named `-webgpu-glslang`, which leads to funny things like this:

```
$ cd -webgpu-glslang/
bash: cd: -w: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
```

Can of course be handled with `cd ./-webgpu-glslang`, but adds a bit of extra friction.

**Comment by pjoe** [comment]
Also causing issues with docker-compose 😟

**Comment by kainino0x** [comment]
Good call. I've renamed it :)
