### ISSUE TITLE
Access to parsed AST?

### ISSUE THREAD

**Issue by npapagna** [kainino0x/glslang.js#6]
Just wonderig if is there a way to get the parsed AST.

AFAIK glslang provides this as part of the standalone tool (though it is a string printed out to the console).

I was hoping there was a way to get the AST model to operate on it.

Thanks in advance!

**Comment by kainino0x** [comment]
Not in this tool right now, no (see the typescript type definition file for the complete API). This project doesn't want to expose the entire API surface of glslang right now; it's focused on producing SPIR-V. Exposing this part of the API would, I think, require translating the C structure data into JS which would be fairly complex.

Perhaps consider doing your AST manipulation work in a C++ program that links against glslang, and giving that program a JS API. You can compile that whole program using Emscripten, and use some of the glslang build flags from this project for reducing glslang's binary size.

**Comment by npapagna** [comment]
@kainino0x got it! Thanks for the quick reply!
